/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class pixy {
  public static int pixy_init() {
    return pixyJNI.pixy_init();
  }

  public static int pixy_get_blocks(int max_blocks, BlockArray blocks) {
    return pixyJNI.pixy_get_blocks(max_blocks, BlockArray.getCPtr(blocks), blocks);
  }

  public static void pixy_close() {
    pixyJNI.pixy_close();
  }

}
